FROM golang:1.19 AS build-env

ENV GOOS=linux

WORKDIR /go/src/github.com/runetale/runetale-oidc-server

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -v ./cmd/db

FROM debian:bullseye

RUN apt-get update && apt-get install -y \
    ca-certificates \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY ./migrations /migrations

COPY --from=build-env /go/src/github.com/runetale/runetale-oidc-server/db /db
RUN chmod u+x /db

COPY docker-entrypoint-db.sh /docker-entrypoint-db.sh
RUN chmod u+x ./docker-entrypoint-db.sh